[package]
name = "ezk-h264"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
bytes = "1.10.0"
openh264 = "0.7.1"
openh264-sys2 = "0.7"
thiserror = "2.0.11"
