[package]
name = "ezk"
version = "0.0.0"
description = "placeholder for future crate"
categories = []
keywords = []

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
